[package]
name = "strange-attractors"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
glam = "0.13"
pollster = "0.2"
wgpu = "0.7"
winit = "0.24"
rand = "0.8"
midir = "0.7"
